# Builds _data/i18n.yml. The latin_25 block is derived from the Ukrainian
# strings using the site's own replacement map - never hand-typed.
require 'yaml'

map = File.read('_tools/replacement.rb').scan(/'([^']+)'\s*=>\s*'([^']*)'/).to_h
translit = ->(s) { s.chars.map { |c| map[c] || c }.join }

en = {
  'site_title'  => 'Ivan Zelot',
  'heading'     => 'Poems',
  'description' => 'A personal blog for poems by Ivan Zelot',
  'search'      => 'Search poems',
  'units'       => 'poem|poems',
  'of'          => 'of',
  'empty'       => 'No poems match “{q}”.',
  'clear'       => 'Clear search',
  'prev'        => 'Previous',
  'next'        => 'Next',
  'pages_label' => 'Poem pages',
  'page_label'  => 'Page',
  'plural'      => 'en'
}

ukr = {
  'site_title'  => 'Іван Зелот',
  'heading'     => 'Поезія',
  'description' => 'Особистий блог поезії Івана Зелота',
  'search'      => 'Пошук віршів',
  'units'       => 'вірш|вірші|віршів',
  'of'          => 'з',
  'empty'       => 'Нічого не знайдено за запитом «{q}».',
  'clear'       => 'Очистити',
  'prev'        => 'Назад',
  'next'        => 'Далі',
  'pages_label' => 'Сторінки',
  'page_label'  => 'Сторінка',
  'plural'      => 'uk'
}

# Transliterate every Ukrainian string; 'plural' is a rule flag, not copy.
latin = ukr.map { |k, v| [k, k == 'plural' ? v : translit.call(v)] }.to_h

data = { 'en' => en, 'ukr' => ukr, 'latin_25' => latin }
File.write('_data/i18n.yml', "# Generated by _tools/gen_i18n.rb - latin_25 is derived from ukr via the\n# transliteration map in _tools/replacement.rb. Edit the script, not this file.\n" + data.to_yaml.sub(/\A---\n/, ''))
puts "latin_25 preview:"
latin.each { |k, v| puts "  #{k}: #{v}" }
